apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  selector:
    matchLabels:
      app: books
  replicas: 1
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: gcr.io/k8s-mn-ci-cd/books:books-0.6
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080