steps:
  - name: 'java:8'
    env: ['GRADLE_USER_HOME=cache']
    entrypoint: 'bash'
    args: ['-c', './gradlew build']
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['gateway:jibDockerBuild']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_IMAGE_NAME}:$TAG_NAME', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME']