steps:
  - name: 'java:8'
    env: ['GRADLE_USER_HOME=cache']
    entrypoint: 'bash'
    args: ['-c', './gradlew build']
  - name: 'gcr.io/cloud-builders/gradle'
    args: [':gateway:jibDockerBuild']
    env:
      - 'GRADLE_USER_HOME=cache'
      - 'GOOGLE_PROJECT_ID=$PROJECT_ID'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gateway:$TAG_NAME', 'gcr.io/$PROJECT_ID/gateway:$TAG_NAME']
